app/users/models.py
"""Snap model."""
from datetime import datetime
from app import db, flask_bcrypt
from sqlalchemy.ext.hybrid import hybrid_property


class User(db.Model):
    """User model class definition."""

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    username = db.Column(db.String(40), unique=True)
    _password = db.Column(db.String(255))
    created_on = db.Column(
        db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        """Show object instance representation."""
        return 'User: {}'.format(self.username)

    @hybrid_property
    def password(self):
        """Encrypted password of a user."""
        return self._password

    @password.setter
    def password(self, password):
        """Encrypt the password on assignment."""
        self._password = flask_bcrypt.generate_password_hash(password)

    def is_authenticated(self):
        """Confirm a user is authenticated."""
        return True

    def is_active(self):
        """Confirm a user is active."""
        return True

    def is_anonymous(self):
        """Confirm a User is anonymous."""
        return False

    def get_id(self):
        """Get user id as a string."""
        return unicode(self.id)

app/__init__.py
"""Initial db configuration."""
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from flask.ext.bcrypt import Bcrypt


app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///../snap.db'
app.config['SECRET_KEY'] = "fsdfsgvetw4hb34523r14"
db = SQLAlchemy(app)
flask_bcrypt = Bcrypt(app)
login_manager = LoginManager()
login_manager.init_app(app)

from app.users import models as user_models
from app.users.views import users


def create_app(config='defualt'):
    """Create app."""
    app.register_blueprint(users, url_prefix='/users')
    return app


@login_manager.user_loader
def load_user(user_id):
    """Get the user using his id."""
    return app.user_models.query.get(int(user_id))

app/users/views.py
"""Snap views."""
from flask import flash, redirect, render_template, url_for
from flask import Blueprint
from flask.ext.wtf import Form
from flask.ext.login import login_user, logout_user, current_user
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length
from app import flask_bcrypt
from models import User

users = Blueprint(
    'users', __name__, template_folder='templates')


class LoginForm(Form):
    """A form subclasss that represents the login form and it's validators."""

    username = StringField('username', validators=[DataRequired()])
    password = PasswordField(
        'password', validators=[DataRequired(), Length(min=6)])


@users.route('/login', methods=['GET', 'POST'])
def login():
    """User login functionality."""
    if current_user.is_authenticated:
        return redirect(url_for('snaps.listing'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(
            username=form.username.data).first()
        if not user:
            flash("No such user exists")
            return render_template('users/login.html', form=form)

        if not flask_bcrypt.check_password_hash(
                user.password, form.password.data):
            flash("invalid password")
            return render_template('users/login.html', form=form)

        login_user(user, remember=True)
        flash("Success! You are logged in.")
        return redirect(url_for("snaps.listing"))

    return render_template('users/login.html', form=form)


@users.route('/logout', methods=['GET'])
def logout():
    """Log the user out."""
    logout_user()
    return redirect(url_for('snaps.listing'))

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>Snap</title>
</head>
<body>
    <h1>Snaps</h1>
    {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
    {% endfor %}

    {% if not current_user.is_authenticated %}
    <a href="{{ url_for('users.login') }}">login</a>
    <a href="{{ url_for('users.logout') }}">logout</a>
    {% endif %}
    <div class="content">
    {% block content %} {% endblock %}
    </div>
</body>
</html>

app/templates/users/login.html
{% extends "layout.html" %}
{% block content %}
<form action="{{ url_for('users.login') }}" method="post">
{{ form.hidden_tag() }}
{{ form.id }}
<div>{{ form.username.label }}: {{ form.username }}</div>
{% if form.username.errors %}
<ul class="errors">{% for errors in form.username.errors %}
    <li>{{ errors }}</li>
{% endfor %}
</ul>
{% endif %}
<div>{{ form.password.label }}: {{ form.password }}</div>
{% if form.password.errors %}
<ul class="errors">{% for error in form.password.errors %}
    <li>{{ error }}</li>
{% endfor %}
</ul>
{% endif %}
<div>
    <input type="submit" value="Login">
</div>
</form>
{% endblock %}